title:            筑梦斋
description:      潇潇洒洒世间游戏，逍逍遥遥笑看天地
url:              blog.qlin.net
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          qiulin
disqus_shortname: qlin
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         About
    url:          /about
  - name:         Feed
    url:          /feed.xml
  - name:         Blog
    url:          http://blog.qlin.net
    external:     true
  - name:         Email
    url:          mailto:xcodeman@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/qiulin
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
