title:            筑梦斋
description:      潇潇洒洒世间游戏，逍逍遥遥笑看天地
url:              blog.qlin.net
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          -eof-
disqus_shortname: qlin
google_analytics_id: # set tracking, UA-XXXX-Y.
google_custom_search_engine_id: 006532633397456281627:-irwrgt0a9w

links:
  - name:         home
    url:          /
  - name:         archives
    url:          http://blog.qlin.net/archives
  - name:         email
    url:          mailto:xcodeman@gmail.com
    external:     true
  - name:         github
    url:          http://github.com/qiulin
    external:     true
  - name:         feed
    url:          /feed.xml

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
